#!/usr/bin/env php
<?php

namespace Butschster\ContextGenerator;

$insidePhar = \str_starts_with(__FILE__, 'phar://');

// load dependencies
$vendorPath = (static function (): string {
    // OK, it's not, let give Composer autoloader a try!
    $possibleFiles = [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../autoload.php',
        __DIR__ . '/vendor/autoload.php',
    ];
    $file = null;
    foreach ($possibleFiles as $possibleFile) {
        if (\file_exists($possibleFile)) {
            $file = $possibleFile;

            break;
        }
    }

    if (null === $file) {
        throw new \RuntimeException('Unable to locate autoload.php file.');
    }

    require_once $file;

    return $file;
})();

use Butschster\ContextGenerator\Cli\ContextGenerator;
use Butschster\ContextGenerator\Cli\GetVersion;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\HttpFactory;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setDefaultCommand('generate');

$vendorPath = \dirname($vendorPath) . '/../';
$versionFile = $vendorPath . '/version.json';
$appPath = \realpath($vendorPath);

$version = \file_exists($versionFile) ? \json_decode(\file_get_contents($versionFile), true) : ['version' => 'dev'];

if ($insidePhar) {
    $appPath = getcwd();
}

$httpClient = new Client();
$httpMessageFactory = new HttpFactory();

$application->add(
    new GetVersion(
        version: $version['version'] ?? 'dev',
    ),
);

$application->add(
    new ContextGenerator(
        rootPath: $appPath,
        outputPath: $appPath . '/.context',
        httpClient: $httpClient,
        requestFactory: $httpMessageFactory,
        urlFactory: $httpMessageFactory,
    ),
);

$application->run();
