#!/usr/bin/env php
<?php

namespace Butschster\ContextGenerator;

$insidePhar = \str_starts_with(__FILE__, 'phar://');

// load dependencies
$appPath = (static function (): string {
    // OK, it's not, let give Composer autoloader a try!
    $possibleFiles = [
        __DIR__ . '/../../autoload.php',
        __DIR__ . '/../autoload.php',
        __DIR__ . '/vendor/autoload.php',
    ];
    $file = null;
    foreach ($possibleFiles as $possibleFile) {
        if (\file_exists($possibleFile)) {
            $file = $possibleFile;

            break;
        }
    }

    if (null === $file) {
        throw new \RuntimeException('Unable to locate autoload.php file.');
    }

    require_once $file;

    return \realpath(\dirname($file) . '/../');
})();

use Butschster\ContextGenerator\Cli\ContextGenerator;
use GuzzleHttp\Client;
use GuzzleHttp\Psr7\HttpFactory;
use Symfony\Component\Console\Application;

$application = new Application();
$application->setDefaultCommand('generate');

if ($insidePhar) {
    $appPath = getcwd();
}

$httpClient = new Client();
$httpMessageFactory = new HttpFactory();

$application->add(
    new ContextGenerator(
        rootPath: $appPath,
        outputPath: $appPath . '/.context',
        httpClient: $httpClient,
        requestFactory: $httpMessageFactory,
        urlFactory: $httpMessageFactory,
    ),
);

$application->run();
